CREATE TABLE APPS.XXHIL_DBA_AZURE_TEST_TAB_03
(
  SRNO  NUMBER(4),
  NAME  VARCHAR2(30 BYTE)
);


ALTER TABLE APPS.XXHIL_DBA_AZURE_TEST_TAB_03 ADD (
  PRIMARY KEY
 (SRNO));

CREATE OR REPLACE SYNONYM APPS.XXHIL_DBA_AZURE_TEST_TAB_03 FOR XXHIL.XXHIL_DBA_AZURE_TEST_TAB_03;

EXIT