CREATE TABLE APPS.XXHIL_DBA_AZURE_TEST_TAB_04
(
  SRNO  NUMBER(4),
  NAME  VARCHAR2(30 BYTE)
);


ALTER TABLE APPS.XXHIL_DBA_AZURE_TEST_TAB_04 ADD (
  PRIMARY KEY
 (SRNO));

CREATE OR REPLACE SYNONYM APPS.XXHIL_DBA_AZURE_TEST_TAB_04 FOR XXHIL.XXHIL_DBA_AZURE_TEST_TAB_04;

EXIT