CREATE TRIGGER APPS.XXHIL_DBA_AZURE_TEST_TRG_05
BEFORE INSERT
ON APPS.XXHIL_DBA_AZURE_TEST_TAB_05 FOR EACH ROW
BEGIN
 INSERT INTO  APPS.XXHIL_DBA_AZURE_TEST_TAB_05
                 (
		srno,
        	name)
values
(
	:NEW.srno,
	SUBSTR(:NEW.name,1,4)
                  );
 EXCEPTION
 WHEN OTHERS THEN
 NULL;
END;
/
exit