CREATE TRIGGER APPS.XXHIL_DBA_AZURE_TEST_TRG_02
BEFORE INSERT
ON APPS.XXHIL_DBA_AZURE_TEST_TAB_02 FOR EACH ROW
BEGIN
 INSERT INTO  APPS.XXHIL_DBA_AZURE_TEST_TAB_02
                 (
		srno,
        	name)
values
(
	:NEW.srno,
	SUBSTR(:NEW.name,1,4)
                  );
 EXCEPTION
 WHEN OTHERS THEN
 NULL;
END;
/
exit