DROP PROCEDURE APPS.XXHIL_DBA_AZURE_TEST_PRC_01;
DROP TRIGGER APPS.XXHIL_DBA_AZURE_TEST_TRG_01;
DROP VIEW APPS.XXHIL_DBA_AZURE_TEST_VW_01;
DROP SYNONYM APPS.XXHIL_DBA_AZURE_TEST_TAB_01;
DROP TABLE XXHIL.XXHIL_DBA_AZURE_TEST_TAB_01;
DROP SEQUENCE XXHIL.XXHIL_DBA_AZURE_TEST_SEQ_01;
