DROP PROCEDURE APPS.XXHIL_DBA_AZURE_TEST_PRC_04;
DROP TRIGGER APPS.XXHIL_DBA_AZURE_TEST_TRG_04;
DROP VIEW APPS.XXHIL_DBA_AZURE_TEST_VW_04;
DROP SYNONYM APPS.XXHIL_DBA_AZURE_TEST_TAB_04;
DROP TABLE XXHIL.XXHIL_DBA_AZURE_TEST_TAB_04;
DROP SEQUENCE XXHIL.XXHIL_DBA_AZURE_TEST_SEQ_04;
