DROP PROCEDURE APPS.XXHIL_DBA_AZURE_TEST_PRC_03;
DROP TRIGGER APPS.XXHIL_DBA_AZURE_TEST_TRG_03;
DROP VIEW APPS.XXHIL_DBA_AZURE_TEST_VW_03;
DROP SYNONYM APPS.XXHIL_DBA_AZURE_TEST_TAB_03;
DROP TABLE XXHIL.XXHIL_DBA_AZURE_TEST_TAB_03;
DROP SEQUENCE XXHIL.XXHIL_DBA_AZURE_TEST_SEQ_03;
