DROP PROCEDURE APPS.XXHIL_DBA_AZURE_TEST_PRC_05;
DROP TRIGGER APPS.XXHIL_DBA_AZURE_TEST_TRG_05;
DROP VIEW APPS.XXHIL_DBA_AZURE_TEST_VW_05;
DROP SYNONYM APPS.XXHIL_DBA_AZURE_TEST_TAB_05;
DROP TABLE XXHIL.XXHIL_DBA_AZURE_TEST_TAB_05;
DROP SEQUENCE XXHIL.XXHIL_DBA_AZURE_TEST_SEQ_05;
