DROP PROCEDURE APPS.XXHIL_DBA_AZURE_TEST_PRC_02;
DROP TRIGGER APPS.XXHIL_DBA_AZURE_TEST_TRG_02;
DROP VIEW APPS.XXHIL_DBA_AZURE_TEST_VW_02;
DROP SYNONYM APPS.XXHIL_DBA_AZURE_TEST_TAB_02;
DROP TABLE XXHIL.XXHIL_DBA_AZURE_TEST_TAB_02;
DROP SEQUENCE XXHIL.XXHIL_DBA_AZURE_TEST_SEQ_02;
