DROP PROCEDURE APPS.XXHIL_DBA_AZURE_TEST_PRC;
DROP TRIGGER APPS.XXHIL_DBA_AZURE_TEST_TRG;
DROP VIEW APPS.XXHIL_DBA_AZURE_TEST_VW;
DROP SYNONYM APPS.XXHIL_DBA_AZURE_TEST_TAB;
DROP TABLE XXHIL.XXHIL_DBA_AZURE_TEST_TAB;
DROP SEQUENCE XXHIL.XXHIL_DBA_AZURE_TEST_SEQ;
