CREATE TABLE APPS.XXHIL_DBA_AZURE_TEST_TAB
(
  SRNO  NUMBER(4),
  NAME  VARCHAR2(30 BYTE)
);


ALTER TABLE APPS.XXHIL_DBA_AZURE_TEST_TAB ADD (
  PRIMARY KEY
 (SRNO));

CREATE OR REPLACE SYNONYM APPS.XXHIL_DBA_AZURE_TEST_TAB FOR XXHIL.XXHIL_DBA_AZURE_TEST_TAB;

EXIT