SET DEFINE OFF;
--
-- XXHIL_INV_ITEM_CONSUMPTION  (Table) 
--
CREATE TABLE XXHIL.XXHIL_INV_ITEM_CONSUMPTION
(
  ORG_ID               NUMBER,
  ITEM_CODE            VARCHAR2(60 BYTE),
  PRIMARY_UOM          VARCHAR2(50 BYTE),
  T_DATE               DATE,
  OPEN_INV_QTY         NUMBER,
  CONSUMPTION_DATE     DATE,
  CONSUMPTION_QTY      NUMBER,
  AVG_CONSUMPTION_QTY  NUMBER,
  RECEIPT_QTY          NUMBER,
  SAFETY_QTY           NUMBER,
  PLANNED_RECEIPTS     NUMBER,
  CLOSING_INV_QTY      NUMBER,
  SUBINVENTORY_CODE    VARCHAR2(20 BYTE),
  ORGANIZATION_CODE    VARCHAR2(10 BYTE),
  OU_NAME              VARCHAR2(30 BYTE),
  CREATED_BY           NUMBER,
  CREATION_DATE        DATE,
  LAST_UPDATED_BY      NUMBER,
  LAST_UPDATE_DATE     DATE,
  LAST_UPDATE_LOGIN    NUMBER,
  REQUEST_ID           NUMBER
);


--
-- XXHIL_INV_ITEM_CONSUMPTION_PK  (Index) 
--
--  Dependencies: 
--   XXHIL_INV_ITEM_CONSUMPTION (Table)
--
CREATE UNIQUE INDEX XXHIL.XXHIL_INV_ITEM_CONSUMPTION_PK ON XXHIL.XXHIL_INV_ITEM_CONSUMPTION
(ORG_ID, ITEM_CODE, T_DATE)
LOGGING
NOPARALLEL
;


--
-- XXHIL_INV_ITEM_CONSUMPTION  (Synonym) 
--
--  Dependencies: 
--   XXHIL_INV_ITEM_CONSUMPTION (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXHIL_INV_ITEM_CONSUMPTION FOR XXHIL.XXHIL_INV_ITEM_CONSUMPTION
/


-- 
-- Non Foreign Key Constraints for Table XXHIL_INV_ITEM_CONSUMPTION 
-- 
ALTER TABLE XXHIL.XXHIL_INV_ITEM_CONSUMPTION ADD (
  CONSTRAINT XXHIL_INV_ITEM_CONSUMPTION_PK
  PRIMARY KEY
  (ORG_ID, ITEM_CODE, T_DATE)
  USING INDEX XXHIL.XXHIL_INV_ITEM_CONSUMPTION_PK
  ENABLE VALIDATE);
/
exit;

