CREATE GLOBAL TEMPORARY TABLE XXHIL.XXHIL_INV_AGING_REP_GTT
   (QTY                                          NUMBER, 
	RATE                                        NUMBER, 
	ORGANIZATION_ID                    NUMBER, 
	STOCK_VALUE                           NUMBER, 
	INVENTORY_ITEM_ID                  NUMBER, 
	SUBINV_CODE                           VARCHAR2(10 ), 
	LOCATOR_ID                              NUMBER, 
	TRANSACTION_DATE                    DATE, 
	ITEM_CODE                               VARCHAR2(40 ), 
	ITEM_DESCRIPTION                    VARCHAR2(240 ), 
	CLASS                                       VARCHAR2(40 ), 
	MAIN_CLASS_VALUE                    VARCHAR2(40 ), 
	GODOWN                                      VARCHAR2(4000 ), 
	ROW1                                         VARCHAR2(40 ), 
	RACK                                            VARCHAR2(40 ), 
	BIN                                                 VARCHAR2(40 ), 
	LOCATION                                        VARCHAR2(40 ), 
	LOCATION_DESC                               VARCHAR2(4000 ), 
	STOCK_COST_CODE                          VARCHAR2(40 ), 
	STOCK_COST_DESC                             VARCHAR2(4000 ), 
	TASK                                                    VARCHAR2(40 ), 
	UOM                                                     VARCHAR2(3 ), 
	AGE                                                     NUMBER, 
	ORIG_DATE_RECEIVED                           VARCHAR2(20 ), 
	ITEM_CATEGORY                                   VARCHAR2(30 ), 
	CATEGORY_ID                                      NUMBER, 
	NATURE                                                  VARCHAR2(40 ), 
	MC                                                        VARCHAR2(40 ), 
	SOURCE                                              VARCHAR2(40 ), 
	MTL_TYPE                                                VARCHAR2(40 ), 
	MTL_TYPE_DESC                                   VARCHAR2(4000 ), 
	SUB_TYPE                                              VARCHAR2(40 ), 
	CAT                                                         VARCHAR2(40 ), 
	PUR_GRP                                               VARCHAR2(40 ), 
	LAST_RCV_DATE                                   DATE, 
	LAST_ISSUE_DATE                                 VARCHAR2(4000 ), 
	MAX_TRX_DATE                                      VARCHAR2(4000 ), 
	LAST_TRX_AGE                                        NUMBER, 
	LAST_TRX_AGE1                                     NUMBER, 
	AGE_IN_MTH                                          NUMBER, 
	AGE_GR_720                                          NUMBER, 
	AGE_BTW_365_720                                 NUMBER, 
	COMP_YEAR_ROUND                                 NUMBER, 
	PROV_AT_25PRC                                       NUMBER, 
	ORGANIZATION_CODE                           VARCHAR2(3 ), 
	ORGANIZATION_NAME                           VARCHAR2(3 ), 
	CREATION_DATE                                   DATE, 
	CATEGORY_CONCAT_SEGS                    VARCHAR2(819 ), 
	EXPIRY_DAYS                                         VARCHAR2(40 ), 
	AGE_CATE                                              VARCHAR2(4000 ), 
	CREATE_TRANSACTION_ID                       NUMBER, 
	UPDATE_TRANSACTION_ID                       NUMBER, 
	LOT_NUMBER                                          VARCHAR2(80 ), 
	EXPIRY_DATE                                         VARCHAR2(20 ), 
	HSN_CODE                                              VARCHAR2(4000 ), 
	AS_DATE                                                 VARCHAR2(20 ), 
	RECEIPT_NUM                                         VARCHAR2(30 ), 
	VENDOR_NAME                                         VARCHAR2(240 ), 
	VENDOR_SITE_CODE                                VARCHAR2(60 ), 
	PR_NUM                                                  VARCHAR2(25 ), 
	REQ_NAME                                                VARCHAR2(4000 ), 
	COLUMN_ABC                                          VARCHAR2(40 ), 
	COLUMN_XYZ                                          VARCHAR2(40 ), 
	COLUMN_OAR                                          VARCHAR2(40 ), 
	COLUMN_VEDI                                         VARCHAR2(40 ), 
	SOURCE_CODE                                         VARCHAR2(30 ), 
	URGENT_FLAG                                         VARCHAR2(1 ), 
	SUBINVENTORY_CODE                               VARCHAR2(10 )
   ) ON COMMIT PRESERVE ROWS ;
   
   /
SHOW ERROR;
EXIT;
   