CREATE OR REPLACE TRIGGER APPS.XXHIL_DTRIG_OPM_DEL_PLAN
BEFORE DELETE ON APPS.XXHIL_OPM_PLANNING_DETAILS FOR EACH ROW

BEGIN
   INSERT INTO APPS.XXHIL_OPM_PLANNING_DETAILS_HIST VALUES 
   (:OLD.ORG,
    :OLD.SALES_ORDER_NUMBER,
    :OLD.LINE_NO,
    :OLD.PROMISE_DATE,
    :OLD.ITEM,
    :OLD.TOTAL_ORDERED_QUANTITY,
    :OLD.TOTAL_ORDERED_UOM,
    :OLD.TOTAL_SECONDARY_QTY,
    :OLD.TOTAL_SECONDARY_UOM,
    :OLD.PLAN_DUE_QUANTITY,
    :OLD.PLAN_DUE_QTY_UOM,
    :OLD.RELEASE_QUANTITY,
    :OLD.LOT_NUMBER,
    :OLD.ON_HAND,
    :OLD.SUGGESTED_START_DATE,
    :OLD.SUGGESTED_END_DATE,
    :OLD.PIECE_BASED_ORDER_QTY,
    :OLD.SHIP_SET_NAME,
    :OLD.MO_PLANNED_ORDER_NO,
    :OLD.RECEIPE_NAME,
    :OLD.RECIPE_VERSION,
    :OLD.ORIGINAL_RESOURCE,
    :OLD.ALTERNATE_RESOURCE,
    :OLD.DECKLE_ORDER,
    :OLD.ATTRIBUTE6,
    :OLD.ATTRIBUTE7,
    :OLD.ATTRIBUTE8,
    :OLD.ATTRIBUTE9,
    :OLD.ATTRIBUTE10,
    :OLD.LAST_UPDATE_LOGIN,
    :OLD.CREATION_DATE,
    :OLD.CREATED_BY,
    :OLD.LAST_UPDATE_DATE,
    :OLD.LAST_UPDATED_BY,
    :OLD.REQUEST_DATE,
    :OLD.INTERFACE_DATE,
    :OLD.INTERFACE_BY
    );
 END;

 /
SHOW ERROR;
EXIT;