SET DEFINE OFF;
--
-- XXHIL_INV_ITEM_PROJECT_PO  (Table) 
--
CREATE TABLE XXHIL.XXHIL_INV_ITEM_PROJECT_PO
(
  ORG_ID                   NUMBER,
  PO_HEADER_ID             NUMBER               NOT NULL,
  PO_LINE_ID               NUMBER               NOT NULL,
  LINE_LOCATION_ID         NUMBER               NOT NULL,
  PO_TYPE                  VARCHAR2(25 BYTE)    NOT NULL,
  PO_NUMBER                VARCHAR2(61 BYTE),
  SUPPLIER_NAME            VARCHAR2(240 BYTE),
  INVENTORY_ITEM_ID        NUMBER,
  ITEM_CODE                VARCHAR2(40 BYTE),
  LINE_NUM                 NUMBER               NOT NULL,
  UNIT_MEAS_LOOKUP_CODE    VARCHAR2(25 BYTE),
  PROMISE_QTY              NUMBER,
  QUANTITY_DUE             NUMBER,
  PROMISED_DATE            DATE,
  QUANTITY_RECEIVED        NUMBER,
  SHIP_TO_ORGANIZATION_ID  NUMBER,
  CREATED_BY           NUMBER,
  CREATION_DATE        DATE,
  LAST_UPDATED_BY      NUMBER,
  LAST_UPDATE_DATE     DATE,
  LAST_UPDATE_LOGIN    NUMBER
);


--
-- XXHIL_INV_ITEM_PROJECT_PO  (Synonym) 
--
--  Dependencies: 
--   XXHIL_INV_ITEM_PROJECT_PO (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXHIL_INV_ITEM_PROJECT_PO FOR XXHIL.XXHIL_INV_ITEM_PROJECT_PO;
/
exit;