CREATE TABLE xxhil.XXHIL_OM_CEDIT_CHK_RELEASE_HDR
(
  "LEVEL_RELEASE"      VARCHAR2(30 BYTE),
  "CREATED_BY"         VARCHAR2(32 BYTE),
  "CREATION_DATE"      DATE,
  "LAST_UPDATED_BY"    VARCHAR2(32 BYTE),
  "LAST_UPDATE_DATE"   DATE,
  "LAST_UPDATE_LOGIN"  VARCHAR2(32 BYTE)
);



CREATE TABLE xxhil.XXHIL_OM_CEDIT_CHK_RELEASE
(
  "USER_NAME"           VARCHAR2(32 BYTE),
  "USER_ID"             NUMBER,
  "DESCRIPTION"         VARCHAR2(30 BYTE),
  "LEVEL_RELEASE"       VARCHAR2(30 BYTE),
  "ZONE_ID"             NUMBER,
  "ZONE"                VARCHAR2(30 BYTE),
  "PRODUCT"             VARCHAR2(32 BYTE),
  "CEDIT_LIMIT_PER"     NUMBER,
  "CEDIT_LIMIT_AMOUNT"  NUMBER,
  "WAREHOUSE"           VARCHAR2(3 BYTE),
  "OPERATING_UNIT"      NUMBER,
  "ORGANIZATION_ID"     VARCHAR2(30 BYTE),
  "ATTRIBUTE1"          VARCHAR2(250 BYTE),
  "ATTRIBUTE2"          VARCHAR2(250 BYTE),
  "ATTRIBUTE3"          VARCHAR2(250 BYTE),
  "ATTRIBUTE4"          VARCHAR2(250 BYTE),
  "ATTRIBUTE5"          VARCHAR2(250 BYTE),
  "CREATED_BY"          VARCHAR2(32 BYTE),
  "CREATION_DATE"       DATE,
  "LAST_UPDATED_BY"     VARCHAR2(32 BYTE),
  "LAST_UPDATE_DATE"    DATE,
  "LAST_UPDATE_LOGIN"   VARCHAR2(32 BYTE),
  "START_DATE"          DATE,
  "END_DATE"            DATE
);


CREATE TABLE xxhil.XXHIL_OM_CEDIT_CHK_NOMINEE
(
  "NOMINEE_USER_NAME"  VARCHAR2(32 BYTE),
  "NOMINEE_USER_DESC"  VARCHAR2(32 BYTE),
  "START_DATE"         DATE,
  "END_DATE"           DATE,
  "USER_NAME"          VARCHAR2(32 BYTE),
  "USER_ID"            NUMBER,
  "NOMINEE_USER_ID"    NUMBER,
  "CREATED_BY"         VARCHAR2(32 BYTE),
  "CREATION_DATE"      DATE,
  "LAST_UPDATED_BY"    VARCHAR2(32 BYTE),
  "LAST_UPDATE_DATE"   DATE,
  "LAST_UPDATE_LOGIN"  VARCHAR2(32 BYTE)
);



CREATE OR REPLACE SYNONYM APPS.XXHIL_OM_CEDIT_CHK_RELEASE_HDR FOR XXHIL.XXHIL_OM_CEDIT_CHK_RELEASE_HDR;

CREATE OR REPLACE SYNONYM APPS.XXHIL_OM_CEDIT_CHK_RELEASE FOR XXHIL.XXHIL_OM_CEDIT_CHK_RELEASE;

CREATE OR REPLACE SYNONYM APPS.XXHIL_OM_CEDIT_CHK_NOMINEE FOR XXHIL.XXHIL_OM_CEDIT_CHK_NOMINEE;

/
EXIT;