Create Table XXHIL.XXHIL_DEBUG_TABLE
(ATTRIBUTE1              VARCHAR2(500),
ATTRIBUTE2              VARCHAR2(500),
ATTRIBUTE3              VARCHAR2(500));

CREATE OR REPLACE SYNONYM APPS.XXHIL_DEBUG_TABLE FOR XXHIL.XXHIL_DEBUG_TABLE;

/
EXIT;
