CREATE TABLE XXHIL.XXHIL_DCS_TRANSACTIONS_RESPONSE 
(ATTRIBUTE1 VARCHAR2(240),ATTRIBUTE2 VARCHAR2(240),ATTRIBUTE3 VARCHAR2(240),ATTRIBUTE4 VARCHAR2(240),ATTRIBUTE5 VARCHAR2(240)
,ATTRIBUTE6 VARCHAR2(500),ATTRIBUTE7 VARCHAR2(500),ATTRIBUTE8 VARCHAR2(500),ATTRIBUTE9 VARCHAR2(2000),ATTRIBUTE10 VARCHAR2(2000)
,DATE_ATTRIBUTE1 DATE,DATE_ATTRIBUTE2 DATE,DATE_ATTRIBUTE3 DATE,DATE_ATTRIBUTE4 DATE,DATE_ATTRIBUTE5 DATE
,NUM_ATTRIBUTE1 NUMBER,NUM_ATTRIBUTE2 NUMBER,NUM_ATTRIBUTE3 NUMBER,NUM_ATTRIBUTE4 NUMBER,NUM_ATTRIBUTE5 NUMBER
,CREATION_DATE DATE, CREATED_BY NUMBER, LAST_UPDATE_DATE DATE, LAST_UPDATE_BY NUMBER, LAST_UPDATE_LOGIN NUMBER
);
CREATE OR REPLACE SYNONYM APPS.XXHIL_DCS_TRANSACTIONS_RESPONSE FOR XXHIL.XXHIL_DCS_TRANSACTIONS_RESPONSE;
/
SHOW ERROR;
EXIT;