name: EBSDEMO - TOSCA Testing

on:
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  test-EBSPROD:
    name: EBSPROD_Test
    runs-on: LTIM_TOSCA_97
    environment: EBSPROD_Test

    env:
      ENVIRONMENT_NAME: EBSPROD_Test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish Tosca JUnit Test Results (Passed)
        uses: dorny/test-reporter@v1
        with:
          name: Tosca JUnit Results (Passed)
          path: D:\EBSHOME_TESTING\results\test\EBSPROD_Test_smoke_result.xml
          reporter: java-junit
          path-replace-backslashes: true

      - name: Publish Tosca JUnit Test Results (Failed)
        if: failure()
        uses: dorny/test-reporter@v1
        with:
          name: Tosca JUnit Results (Failed)
          path: D:\EBSHOME_TESTING\results\27\EBSPROD_Test_smoke_result.xml
          reporter: java-junit
          path-replace-backslashes: true
