name: EBSDEMO - TOSCA Testing

on:
  workflow_dispatch:

jobs:
  test-EBSPROD:
    name: EBSPROD_Test
    runs-on: LTIM_TOSCA_97
    environment: EBSPROD_Test

    env:
      ENVIRONMENT_NAME: EBSPROD_Test
    
    steps:
      - name: Publish JUnit Test Results to GitHub Actions passed
        uses: dorny/test-reporter@v1
        with:
          name: Tosca JUnit Results
          path: D:\EBSHOME_TESTING\results\test\EBSPROD_Test_smoke_result.xml

          reporter: java-junit

    
      - name: Publish JUnit Test Results to GitHub Actions failed
        uses: dorny/test-reporter@v1
        with:
          name: Tosca JUnit Results
          path: D:\EBSHOME_TESTING\results\27\EBSPROD_Test_smoke_result.xml

          reporter: java-junit


